classroom/api/urls.py
from django.db import router
from django.urls import path
from rest_framework import routers
from . import views
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('',views.getRoutes),
    path('users/',views.getUser.as_view()),
    path('oursystem/',views.getSystem),
    path('oursystem/<str:pk>/',views.getClass),
]

classroom/classroom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import user
import oursystem

urlpatterns = [
    path("", include("user.urls")),
    path("oursystem/", include("oursystem.urls")),
    path('admin/', admin.site.urls),
    path('api/',include("api.urls"))
    
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classroom/oursystem/urls.py
from django.urls import path
from . import views

app_name='oursystem'
urlpatterns = [
    path('', views.SubjectListView.as_view(), name='subject_list'),
    path('<slug:slug>/', views.CourseListView.as_view(), name='course_list'),
    path('<slug:slug>/create/', views.CourseCreateView.as_view(), name='course_create'),
    path('<str:subject>/<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('<str:subject>/<slug:slug>/update/', views.CourseUpdateView.as_view(), name='course_update'),
    path('<str:subject>/<slug:slug>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),
]

classroom/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{%block title%}{%endblock%}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app.css' %}">

  </head>
  <body>
    <!-- navigation bar -->
              <nav class="navbar navbar-expand-lg  navbar-light bg-light fixed-top scrolling-navbar">
                <div class="container" >
                      <a class="navbar-brand" href="{% url 'index' %}" style="color:#ff5722;" >Home</a>
                      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                           aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                           <span class="navbar-toggler-icon"></span>
                       </button>
                      <div class="collapse navbar-collapse" id="basicExampleNav" >
                        <ul class=" navbar-nav  mr-auto smooth-scroll " >
                                <li class="nav-item">
                                   <a class="nav-link" href="{% url 'oursystem:subject_list' %}">Classroom</a>
                                </li> 
                                {% if user.is_superuser %}
                                <li class="nav-item ">
                                   <a class="nav-link" href="{% url 'admin:index' %}">Admin</span> </a>
                                </li>
                                {%endif%}
                                {% if user.is_authenticated %}
                                    <li class="nav-item  ">
                                     <a class="nav-link" href="{% url 'user_logout' %}">Logout</a>
                                    </li>
                                {% else %}
                                    <li class="nav-item ">
                                        <a class="nav-link" href="{% url 'user_login' %}">Login</a>
                                    </li>
                                    <li class="nav-item " >
                                       <a class="nav-link" href="{% url 'register' %}">Register</span> </a>
                                    </li>
                                {% endif %}
                                
                        </ul>
                      </div>
                </div>
              </nav>
          {% block image_block %}
          {% endblock %}


    <div class="container">
        {%block content%}
        {%endblock%}
    </div>

    <footer class="page-footer" style="background-color:#b2ebf2;">
      <div class="container">
        <div class="row mt-4">
                  <div class="col-md-4 mt-4">
                            <h3>About Us</h3> <br>
                            <p></p>
                  </div>
                  <div class="col-md-4 mt-4">
                            <h3>Other Useful Stuff</h3>
                            <ul>
                              <li>Item 1</li>
                              <li>Item 2</li>
                              <li>Item 3</li>
                            </ul>
                  </div>
                  <div class="col-md-4 mt-4">
                            <h3>Contact Us</h3>
                            <ul>
                              <li>Address: </li>
                              <li>info@gmail.com</li>
                              <li>contact number</li>
                            </ul>
                  </div>
        </div>
      </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <script type="text/javascript" src=""></script>
  </body>
</html>