classroom/api/urls.py
from django.db import router
from django.urls import path
from rest_framework import routers
from . import views
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('',views.getRoutes),
    path('users/',views.getUser.as_view()),
    path('oursystem/',views.getSystem),
    path('oursystem/<str:pk>/',views.getClass),
]

classroom/classroom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import user
import oursystem

urlpatterns = [
    path("", include("user.urls")),
    path("oursystem/", include("oursystem.urls")),
    path('admin/', admin.site.urls),
    path('api/',include("api.urls"))
    
]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classroom/oursystem/urls.py
from django.urls import path
from . import views

app_name='oursystem'
urlpatterns = [
    path('', views.SubjectListView.as_view(), name='subject_list'),
    path('<slug:slug>/', views.CourseListView.as_view(), name='course_list'),
    path('<slug:slug>/create/', views.CourseCreateView.as_view(), name='course_create'),
    path('<str:subject>/<slug:slug>/', views.CourseDetailView.as_view(), name='course_detail'),
    path('<str:subject>/<slug:slug>/update/', views.CourseUpdateView.as_view(), name='course_update'),
    path('<str:subject>/<slug:slug>/delete/', views.CourseDeleteView.as_view(), name='course_delete'),
]

classroom/oursystem/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.template.defaultfilters import slugify
import os
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.



class Subject(models.Model):
    subject_id = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField(max_length=500,blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.subject_id)
        super().save(*args, **kwargs)


def save_course_files(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    # get filename
    if instance.course_id:
        filename = 'course_files/{}/{}.{}'.format(instance.course_id,instance.course_id, ext)
        if os.path.exists(filename):
            new_name = str(instance.course_id) + str('1')
            filename =  'course_images/{}/{}.{}'.format(instance.course_id,new_name, ext)
    return os.path.join(upload_to, filename)

class Course(models.Model):
    course_id = models.CharField(max_length=100,)
    created_by = models.ForeignKey(User,on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='courses')
    name = models.CharField(max_length=250)
    code = models.CharField(max_length=7, auto_created=True, unique=True)
    section = models.PositiveSmallIntegerField(verbose_name="Section no.")
    slug = models.SlugField(null=True, blank=True)
    video = models.FileField(upload_to=save_course_files,verbose_name="Video", blank=True, null=True)
    ppt = models.FileField(upload_to=save_course_files,verbose_name="Presentations", blank=True)
    pdf = models.FileField(upload_to=save_course_files,verbose_name="pdf", blank=True)

    class Meta:
        ordering = ['section']
        ordering=['code']
    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('oursystem:course_list', kwargs={'slug':self.subject.slug })
        

    

class Comment(models.Model):
    course_name = models.ForeignKey(Course, null=True, on_delete=models.CASCADE,related_name='comments')
    comm_name = models.CharField(max_length=100, blank=True)
    # reply = models.ForeignKey("Comment", null=True, blank=True, on_delete=models.CASCADE,related_name='replies')
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.comm_name = slugify("comment by" + "-" + str(self.author) + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.comm_name

    class Meta:
        ordering = ['-date_added']

class Reply(models.Model):
    comment_name = models.ForeignKey(Comment, on_delete=models.CASCADE,related_name='replies')
    reply_body = models.TextField(max_length=500)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "reply to " + str(self.comment_name.comm_name)

classroom/oursystem/forms.py
from django import forms
from .models import  Course, Comment, Reply

class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('course_id','name','subject','section','code','ppt','pdf')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {"body":"Comment:"}

        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Enter Your Comment"}),
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ReplyForm, self).__init__(*args, **kwargs)

classroom/oursystem/views.py
from django.views.generic.base import View
from oursystem.models import  Course, Subject, Comment
from django.db import models
from django.shortcuts import render, redirect
from django.views.generic import (TemplateView, CreateView,
                                    UpdateView, DeleteView, DetailView, ListView, FormView)
from django.urls import reverse_lazy, reverse
from .forms import CourseForm, CommentForm, ReplyForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
# Create your views here.


class SubjectListView(ListView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'oursystem/subject_list_view.html'

class CourseListView(DetailView):
    context_object_name = 'subjects'
    model = Subject
    template_name = 'oursystem/course_list_view.html'


"""class JoinClass(DetailView, FormView):
    form_class = CourseForm
    fields = ('code')
    context_object_name = 'subjects'
    model = Subject
    template_name = 'oursystem/join_class.html'


    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        self.object = self.get_object()
        return reverse_lazy('oursystem:course_list',kwargs={'slug':self.object.slug})"""


class CourseDetailView(DetailView, FormView):
    context_object_name = 'courses'
    model = Course
    template_name = 'oursystem/course_detail_view.html'
    form_class = CommentForm
    second_form_class = ReplyForm

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(request=self.request)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(request=self.request)
        # context['comments'] = Comment.objects.filter(id=self.object.id)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)
        # print("the form name is : ", form)
        # print("form name: ", form_name)
        # print("form_class:",form_class)

        if form_name=='form' and form.is_valid():
            print("comment form is returned")
            return self.form_valid(form)
        elif form_name=='form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)


    def get_success_url(self):
        self.object = self.get_object()
        subject = self.object.subject
        return reverse_lazy('oursystem:course_detail',kwargs={'subject':subject.slug,
                                                             'slug':self.object.slug})
    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.course_name = self.object.comments.name
        fm.course_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.author = self.request.user
        fm.comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())


class CourseCreateView(CreateView):
    #fields = ('course_id','name','section','code')
    form_class = CourseForm
    context_object_name = 'subject'
    model= Subject
    template_name = 'oursystem/course_create.html'

    def get_success_url(self):
        self.object = self.get_object()
        return reverse_lazy('oursystem:course_list',kwargs={'slug':self.object.slug})


    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.subject = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

class CourseUpdateView(UpdateView):
    fields = ('name','section','ppt','pdf')
    model= Course
    template_name = 'oursystem/course_update.html'
    context_object_name = 'courses'

class CourseDeleteView(DeleteView):
    model= Course
    context_object_name = 'courses'
    template_name = 'oursystem/course_delete.html'

    def get_success_url(self):
        print(self.object)
        subject = self.object.subject
        return reverse_lazy('oursystem:course_list',kwargs={'slug':subject.slug})

classroom/oursystem/templates/oursystem/course_create.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Classroom Create {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Classroom Creation </h2>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4"></h4>
       </div>
    </div>
  </div>
</header>
{% endblock %}

{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Create a Classroom</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text"></p>
                </div>
              </div>
</section>


<form method="post" enctype="multipart/form-data">
  <div class="form-group">
  {% csrf_token %}
  {{form|crispy}}
  <input class="btn btn-success btn-lg btn-block" type="submit" value="Create">
  </div>
</form>

{% endblock %}

classroom/oursystem/templates/oursystem/course_delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Course Delete {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Course Deletion </h2>
        
      

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4"></h4>
      </div>
    </div>
  </div>
</header>
{% endblock %}



{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Delete {{courses.name}}</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text"></p>
                </div>
              </div>
</section>

<h3 class="mb-4" style="color:#ff5722;">Are you sure you want to delete {{courses.name}}?</h3>

<form method="post">
  {% csrf_token %}
  <div class="row">
        <div class="col-md-4 mb-3 mr-3">
                <input type="submit" value="Delete" class="btn btn-danger btn-block">
        </div>
        <div class="col-md-4 mb-3 mr-3">
                <a href="{% url 'oursystem:course_detail' subject=courses.subject.slug slug=courses.slug %}" class="btn btn-warning btn-block">Cancel Deletion</a>
        </div>
  </div>
</form>

{% endblock %}

classroom/oursystem/templates/oursystem/course_detail_view.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %} {{courses.name}} {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" >Section-{{courses.section}}: {{courses.name}}</h2>
        
        

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4"></h4>
      </div>
    </div>
  </div>
</header>
{% endblock %}

{% block content %}

<section class="text-center">
    <h2 class="mb-0 mt-5 font-weight-bold" style="color:#ff5722;">Course details</h2>
    <div class="row d-flex justify-content-center mb-3">
      <blockquote class="blockquote mt-0">
        <footer class="blockquote-footer">Created on {{courses.created_at}} by <cite title="Source Title">{{courses.created_by}}</cite></footer>
        </blockquote>
    </div>

    <!-- download cards -->
    <div class="row d-flex justify-content-center mb-3 mt-3">
      <!-- download presentations -->
                <div class="col-md-4 mb-4 mt-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Download Presentations</h5>
                      {% if courses.ppt %}
                      <p class="card-text">Download presentations from this course</p>
                      <a href="{{courses.ppt.url}}" download>
                      <button type="button" class="button-les"><span>Download</span></button>
                      </a>
                      {% else %}
                      <p class="card-text" > No PPT available</p>
                      {% endif %}

                    </div>
                  </div>
                </div>
      <!-- download pdf -->
                <div class="col-md-4 mb-4 mt-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">Download Pdf</h5>
                      {% if courses.pdf %}
                      <p class="card-text">Download pdf from this course</p>
                      <a href="{{courses.pdf.url}}" download>
                      <button type="button" class="button-les"><span>Download</span></button>
                      </a>
                      {% else %}
                      <p class="card-text">pdf not available</p>
                      {%endif%}

                    </div>
                  </div>
                </div>
      
    </div>
    <!-- update and delete button -->
    <div class="row d-flex justify-content-center mb-3 mt-3">
        {% if user.userprofileinfo.user_type == 'teacher' or user.is_superuser %}
        <div class="col-md-6 mb-3 text-center">
            <a href="{% url 'oursystem:course_update'  subject=courses.subject.slug slug=courses.slug %}" class="btn btn-warning btn-lg mr-4 btn-block">Update Course</a>
        </div>
        <div class="col-md-6">
            <a href="{% url 'oursystem:course_delete'  subject=courses.subject.slug slug=courses.slug %}" class="btn btn-danger btn-lg mr-4 btn-block"> Delete Course </a>
        </div>
        {% endif %}
      </div>
</section>

<hr class="my-5" style="color:#ff5722;">

<!-- Comments section -->

<section >
    <h2 class="mb-4 mt-5 font-weight-bold" style="color:#ff5722;">Questions And Queries</h2>
    <h4 class="mt-2 font-weight-bold" style="color:#ff5722;">Post your comment or question below:</h4>
    <br><br>
    <div class="container row">
      <div class="col-md-6">
          <form method="post">
            <div class="form-group">
                 {% csrf_token %}
                 {{form|crispy}}
            <input type="submit" name="form" value="Add Comment" class="btn btn-primary btn-sm">
            </div>
          </form>

      </div>
    </div>
    <div class="row">
      {% for comment in courses.comments.all %}
      <div class="col-md-8 mt-2 mb-2">
                      <div class="media border p-3">
                          <img src="" alt="" class="mr-3 mt-3 rounded-circle" style="width:60px;">
                          <div class="media-body">
                                    <h4>{{comment.author}} <small><i>Posted on {{comment.date_added}}</i></small></h4>
                                    <p>{{comment.body}}</p>
                            {% for reply in comment.replies.all %}
                                        <div class="media p-3">
                                                <img src="" alt="" class="mr-3 mt-3 rounded-circle" style="width:45px;">
                                        <div class="media-body">
                                                <h5>{{reply.author}} <small><i>Posted on {{reply.date_added}}</i></small></h5>
                                                <p>{{reply.reply_body}}</p>
                                          </div>
                                        </div>
                            {% endfor %}
                            <!-- form to post reply -->
                            <form method="post">
                                  <input type="hidden" name="comment.id" value="{{comment.id}}">
                                  <input type="hidden" name="comment.comm_name" value="{{comment.comm_name}}">
                                  {% csrf_token %}
                                  {{form2.as_p}}
                                  <input type="submit" name="form2" value="Add Reply" class="btn btn-warning btn-sm">
                            </form>
                          </div>
                  </div>
      </div>
      {% endfor %}
    </div>


</section>


{%endblock%}

classroom/oursystem/templates/oursystem/course_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{subjects.name}} {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > {{subjects.name}} </h2>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4"></h4>
  </div>
</header>
{% endblock %}


{% block content %}
<section id="best-features" class="text-center">
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8 mb-5">
                  <p class="grey-text"></p>
                </div>
              </div>
              <!-- class row2 for cards -->
              <div class="row d-flex justify-content-center mb-3">
                {% for course in subjects.courses.all %}
                <div class="col-sm-4 mb-4">
                  <div class="card box-shadow-hover">
                    <div class="card-body">
                      <h5 class="card-title">{{course.course_id}}, Section-{{course.section}}</h5>
                      {% if user.userprofileinfo.user_type == 'teacher' or user.is_superuser %}
                        <h5 class="card-title">Class code: {{course.code}} </h5>
                        <a href="{% url 'oursystem:course_detail' slug=course.slug subject=subjects.slug %}" >
                        <button type="button" class="button-les"><span>Enter class</span></button>
                        </a>
                      {% endif %}
                      {% if user.userprofileinfo.user_type == 'student' %}
                        <a href="{% url 'oursystem:course_detail' slug=course.slug subject=subjects.slug %}"> 
                        <button type="button" class="button-les"><span>Join class</span></button>
                         </a>
                        
                      {% endif %}
                    </div>
                  </div>
                </div>
                {% endfor %}
              </div>
        <div class="row d-flex justify-content-center mb-3">
          {% if user.userprofileinfo.user_type == 'teacher' or user.is_superuser %}
           <a href="{% url 'oursystem:course_create' slug=subjects.slug %}"><button type="button" class="btn btn-success btn-lg btn-bloc" > Create new classroom </button> </a>
          {% endif %}
        </div>

</section>






{%endblock%}

classroom/oursystem/templates/oursystem/course_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Course Update {% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Course Update </h2>
        
        

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
      </div>
    </div>
  </div>
</header>
{% endblock %}


{% block content %}

<section id="best-features" class="text-center">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Update {{courses.name}}</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text"></p>
                </div>
              </div>
</section>


<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form|crispy}}
  <div class="row">
        <div class="col-md-4 mb-3 mr-3">
                <input type="submit" value="Update" class="btn btn-warning btn-block">
        </div>
        <div class="col-md-4 mb-3 mr-3">
                <a href="{% url 'oursystem:course_detail' subject=courses.subject.slug slug=courses.slug %}" class="btn btn-danger btn-block">Cancel Update</a>
        </div>
</div>
</form>

{% endblock %}

classroom/oursystem/templates/oursystem/join_class.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Join This class{% endblock %}

{% block image_block %}
<header class="info-header">
  <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
    <div class="row d-flex justify-content-center text-center">
      <div class="col-md-10 text-white">
        <!-- heading -->
        <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > </h2>

        <!-- divider -->
        <hr style="color:#ff5722;">

        <!-- description -->
        <h4 class="white-text my-4"></h4>
      </div>
      </div>
  </div>
</header>
{% endblock %}

{% block content %}

<section class="text-center mt-4">
              <h2 class="mb-5 font-weight-bold" style="color:#ff5722;">Join Classroom here</h2>
              <!-- class row for description-->
              <div class="row d-flex justify-content-center mb-4">
                <!-- class column -->
                <div class="col-md-8">
                  <p class="grey-text"></p>
                </div>
              </div>
              <div class="row d-flex justify-content-center mb-4">
                <form method="post">
                  <div class="form-group">


                  {% csrf_token %}
                  
                  <div class="col-md-12">
                    <div class="row">
                    

                  <label for="code">Class code:</label>
                  <input type="text" name="code" placeholder="Class Code" class="form-control">
                  </div>
                  <div class="row justify-content-center">
                    <input type="submit" value="Join Classroom" class="btn btn-success btn-lg mt-3"> 
                    
                    
                  </div>
                  </div>
                  </div>
                </form>
              </div>
</section>
{%endblock%}

classroom/oursystem/templates/oursystem/subject_list_view.html
{% extends 'base.html' %}
  {% load static %}
  {% block title %} Subjects {% endblock %}


  {% block image_block %}
  <header class="info-header">
    <div id="page-intro" class="container-fluid d-flex align-items-center justify-content-center ">
      <div class="row d-flex justify-content-center text-center">
        <div class="col-md-10 text-white">
          <!-- heading -->
          <h2 class="display-4 font-weight-bold  p-5 " style="color:#ff5722;" > Classroom </h2>

          <!-- divider -->
          <!-- <hr style="color:#ff5722;"> -->

          <!-- description -->
          <!-- <h4 class="white-text my-4"></h4>-->
        </div>
      </div>
    </div>
  </header>
  {% endblock %}

  {% block content %}
  <section id="best-features" class="text-center">
                <h2 class="mb-5 mt-5 font-weight-bold" style="color:#ff5722;">Subjects</h2>
                <!-- class row for description-->
                <div class="row d-flex justify-content-center mb-4">
                  <!-- class column -->
                  <div class="col-md-8 mb-5">
                    <p class="grey-text"></p>
                  </div>
                </div>
                <!-- class row2 for cards -->
                <div class="row d-flex justify-content-center mb-3">
                {% for subject in subjects.all %}
                  <div class="card mb-4 sm-4 ml-4 box-shadow-hover" >
                      <div class="row no-gutters">
                            <div class="col-md-8">
                              <div class="card-body">
                                <h4 class="card-title" style="color:#ff5722;">{{subject.name}}</h4>
                                <!-- <p class="card-text">{{subject.description|truncatechars:15}}</p>
                                <p class="card-text"><small class="text-muted"></small></p> -->
                                  {% if user.is_authenticated %}
                                    <a href="{% url 'oursystem:course_list' slug=subject.slug %}"><button class="button-les"> <span> Get courses</span></button></a>
                                  {%else%}
                                    <p>Please register or login</p>
                                    <!-- <a href="{% url 'user_login' %}" class="btn btn-std" style="background-color:#00bcd4;">Login</a>
                                         <a href="{% url 'register' %}" class="btn btn-primary" style="background-color:#00bcd4;">Register</a>
                                    -->
                                  {%endif%}
                              </div>
                            </div>
                      </div>
                  </div>
                {% endfor %}
                </div>
  </section>
  {%endblock%}